title: Mythara News Network
description: Eight reporters read the news every morning, then tell you what they noticed.
baseurl: "/Mythara-Blog"
url: "https://herbievelezjr.github.io"
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
